.TH "arch-linux" "1" "October 2018" "NULL" "Installation Guide"
.SH
Installation guide
.PP
This document is a guide for installing Arch Linux from the live system \
booted with the official installation image. Before installing, it would \
be advised to view the FAQ. For conventions used in this document, see \
Help:Reading. In particular, code examples may contain placeholders \
(formatted in italics) that must be replaced manually.
.PP
For more detailed instructions, see the respective ArchWiki articles or \
the various programs' man pages, both linked from this guide. For \
interactive help, the IRC channel and the forums are also available.
.pp
Arch Linux should run on any x86_64-compatible machine with a minimum of \
512 MB RAM. A basic installation with all packages from the base group \
should take less than 800 MB of disk space. As the installation process \
needs to retrieve packages from a remote repository, this guide assumes a \
working internet connection is available.
.SH
1) Pre-installation
.PP
Download and boot the installation medium as explained in Getting and
installing Arch. You will be logged in on the first virtual console as
the root user, and presented with a Zsh shell prompt.
.PP
To switch to a different console—for example, to view this guide with
ELinks alongside the installation—use the Alt+arrow shortcut. To edit
configuration files, nano, vi and vim are available.
.PP
\fB1.1) Set the Keyboard layout\fR
.TP
The default console keymap is US. Available layouts can be listed with:
\fB# ls /usr/share/kbd/keymaps/**/*.map.gz\fR
.TP
To modify the layout, append a corresponding file name to \
\fBloadkeys\fR(1), omitting path and file extension. For example, to set \
a German keyboard layout:
\fB# loadkeys de-latin1\fR
.PP
Console fonts are located in \fI/usr/share/kbd/consolefonts/\fR and can \
likewise be set with \fBsetfont\fR(8).
.PP
\fB1.2) Verify the boot mode\fR
.TP
If UEFI mode is enabled on an UEFI motherboard, Archiso will boot Arch \
Linux accordingly via systemd-boot. To verify this, list the efivars \
directory:
\fB# ls /sys/firmware/efi/efivars\fR
.PP
If the directory does not exist, the system may be booted in BIOS or CSM \
mode. Refer to your motherboard's manual for details.
.PP
\fB1.3) Connect to the internet\fR
.TP
The installation image enables the dhcpcd daemon for wired network \
devices on boot. The connection may be verified with ping:
\fB# ping archlinux.org\fR
.PP
If no connection is available, stop the dhcpcd service with \fIsystemctl \
stop dhcpcd@interface\fR where the interface name can be tab-completed. \
Proceed to configure the network as described in Network configuration.
.PP
\fB1.4) Update the system clock\fR
.TP
Use \fBtimedatectl\fR(1) to ensure the system clock is accurate:
\fB# timedatectl set-ntp true\fR
.PP
To check the service status, use \fItimedatectl status\fR.
.PP
\fB1.5) Partition the disks\fR
.TP
When recognized by the live system, disks are assigned to a block device \
such as \fI/dev/sda\fR or \fI/dev/nvme0n1\fR. To identify these devices, \
use lsblk or fdisk.
\fB# fdisk -l\fR
.PP
Results ending in \fIrom\fR, \fIloop\fR or \fIairoot\fR may be ignored.
.TP
The following partitions are required for a chosen device:
\fB.\fR One partition for the root directory \fI/\fR.
.br
\fB.\fR If UEFI is enabled, an EFI system partition.
.PP
\fINote\fR: Swap space can be set on a separate partition or a swap file.
.TP
To modify partition tables, use fdisk or parted.
\fB# fdisk /dev/sda\fR
.PP
\fINote\fR: If you want to create any stacked block devices for LVM, \
disk encryption or RAID, do it now.
.PP
\fB1.6) Format the partitions\fR
.TP
Once the partitions have been created, each must be formatted with an \
appropriate file system. For example, to format the root partition on \
\fI/dev/sda1\fR with \fIext4\fR, run:
\fB# mkfs.ext4 /dev/sda1\fR
.TP
If you created a partition for swap (for example \fI/dev/sda3\fR), \
initialize it with mkswap:
\fB# mkswap /dev/sda3\fR
.br
\fB# swapon /dev/sda3\fR
.PP
\fB1.7) Mount the file systems\fR
.TP
Mount the file system on the root partition to \fI/mnt\fR, for example:
\fB# mount /dev/sda1 /mnt\fR
.TP
Create mount points for any remaining partitions and mount them accordingly:
\fB# mkdir /mnt/boot\fR
.br
\fB# mount /dev/sda2 /mnt/boot\fR
.PP
genfstab will later detect mounted file systems and swap space.
.SH
\fB2) Installation\fR
.PP
\fB2.1) Select the mirrors\fR
.PP
Packages to be installed must be downloaded from mirror servers, which \
are defined in \fI/etc/pacman.d/mirrorlist\fR. On the live system, all \
mirrors are enabled, and sorted by their synchronization status and speed \
at the time the installation image was created.
.PP
The higher a mirror is placed in the list, the more priority it is given \
when downloading a package. You may want to edit the file accordingly, \
and move the geographically closest mirrors to the top of the list, \
although other criteria should be taken into account.
.PP
This file will later be copied to the new system by pacstrap, so it is \
worth getting right.
.PP
\fB2.2) Install the base packages\fR
.TP
Use the pacstrap script to install the base package group:
\fB# pacstrap /mnt base\fR
.PP
This group does not include all tools from the live installation, such as \
btrfs-progs or specific wireless firmware; see packages.x86_64 for \
comparison.
.PP
To install packages and other groups such as base-devel, append the names \
to pacstrap (space separated) or to individual pacman commands after the \
#Chroot step.
.SH
\fB3) Configure the system\fR
.PP
\fB3.1) Fstab\fR
.TP
Generate an fstab file (use \fI-U\fR or \fI-L\fR to define by UUID or \
labels, respectively):
\fB# genfstab -U /mnt >> /mnt/etc/fstab\fR
.PP
Check the resulting file in \fI/mnt/etc/fstab\fR afterwards, and edit it \
in case of errors.
.PP
\fB3.2) Chroot\fR
.TP
Change root into the new system:
\fB# arch-chroot /mnt\fR
.PP
\fB3.3) Time zone\fR
.TP
Set the time zone:
\fB# ln -sf /usr/share/zoneinfo/Region/City /etc/localtime\fR
.TP
Run \fBhwclock\fR(8) to generate \fI/etc/adjtime\fR:
\fB# hwclock --systohc\fR
.PP
This command assumes the hardware clock is set to UTC. See Time#Time \
standard for details.
.PP
\fB3.4) Localization\fR
.TP
Uncomment \fIen_US.UTF-8 UTF-8\fR and other needed locales in \
\fI/etc/locale.gen\fR, and generate them with:
\fB# locale-gen\fR
.TP
Set the \fILANG\fR variable in \fBlocale.conf\fR(5) accordingly, \
for example:
\fI/etc/locale.conf\fR
.br
LANG=en_US.UTF-8
.TP
If you set the keyboard layout, make the changes persistent in \
\fBvconsole.conf\fR(5):
\fI/etc/vconsole.conf\fR
.br
KEYMAP=de-latin1
.PP
\fB3.5) Network configuration\fR
.TP
Create the hostname file:
\fI/etc/hostname\fR
.br
myhostname
.TP
Add matching entries to \fBhosts\fR(5):
\fI/etc/hosts\fR
.br
127.0.0.1	localhost
.br
::1		localhost
.br
127.0.1.1	myhostname.localdomain	myhostname
.PP
If the system has a permanent IP address, it should be used instead \
of \fI127.0.1.1\fR.
.PP
Complete the network configuration for the newly installed environment.
.PP
\fB3.6) Initramfs\fR
.PP
Creating a new initramfs is usually not required, because mkinitcpio was \
run on installation of the linux package with pacstrap.
.TP
For special configurations, modify the \fBmkinitcpio.conf\fR(5) file and \
recreate the initramfs image:
\fB# mkinitcpio -p linux\fR
.PP
\fB3.7) Root password\fR
.TP
Set the root password:
\fB# passwd\fR
.PP
\fB3.8) Boot loader\fR
.PP
A Linux-capable boot loader must be installed in order to boot Arch \
Linux. See Category:Boot loaders for available choices.
.PP
If you have an Intel or AMD CPU, enable microcode updates.
.SH
\fB4) Reboot\fR
.PP
Exit the chroot environment by typing \fIexit\fR or pressing \fICtrl+D\fR.
.PP
Optionally manually unmount all the partitions with \fIumount -R /mnt\fR: \
this allows noticing any "busy" partitions, and finding the cause with \
\fBfuser\fR(1).
.PP
Finally, restart the machine by typing \fIreboot\fR: any partitions still \
mounted will be automatically unmounted by systemd. Remember to remove \
the installation media and then login into the new system with the root \
account.
.SH
\fB5) Post-installation\fR
.PP
See General recommendations for system management directions and \
post-installation tutorials (like setting up a graphical user interface, \
sound or a touchpad).
.PP
For a list of applications that may be of interest, see List of applications.
